### ISSUE TITLE
typerep of an abstract type prints  a strange message.

### ISSUE THREAD

**Issue by camlspotter** [janestreet/ppx_typerep_conv#1]
For example, if I write

``` ocaml
type t [@@deriving typerep]
```

then, `ppx_typerep_conv` says: `typerep cannot be applied on abstract types, except like 'type t [@deriving typerep ~abstract]`.  It has two problems:
- `@` sign is printed only once.  It is a simple buggy use of `@@` in printf format at line 643 of ppx_typerep_conv.ml.  It should be `@@@@`.
- If I use `type t [@@deriving typerep ~abstract]`, ppx_typerep_conv says: `Unrecognized [@@deriving] option syntax`.  I use ppx_deriving.3.3.  Is it a correct way to specify the argument?  Or, do I need to use ppx_deriving of another version?

**Comment by lpw25** [comment]
> I use ppx_deriving.3.3. Is it a correct way to specify the argument? Or, do I need to use ppx_deriving of another version?

I think the best way is using [ppx_driver](https://github.com/janestreet/ppx_driver), which is what we use internally. The second point is probably a small issue with the ppx_deriving compatibility layer.

**Comment by ghost** [comment]
For the second point, `ppx_type_conv` uses labelled arguments, while `ppx_deriving` uses records. So when using `ppx_deriving` you need to write: `[@@deriving typerep { abstract }]`

**Comment by v-gb** [comment]
Amazingly, the missing `@` in the error message haven't been fixed, so I just did that.
I think interoperability with ppx_deriving works differently now (no translation of syntax), which should stop the second problem.

**Comment by aalekseyev** [comment]
The fix is in commit fe9e47a75c004c4d765722848d6de29ef1cf830d.
